/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace PolygonChatRegistry {
  export type ConversationMetaStruct = {
    conversationId: BytesLike;
    userA: AddressLike;
    userB: AddressLike;
    latestCid: string;
    messageCount: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type ConversationMetaStructOutput = [
    conversationId: string,
    userA: string,
    userB: string,
    latestCid: string,
    messageCount: bigint,
    updatedAt: bigint
  ] & {
    conversationId: string;
    userA: string;
    userB: string;
    latestCid: string;
    messageCount: bigint;
    updatedAt: bigint;
  };

  export type ProfileStruct = {
    username: string;
    displayName: string;
    bio: string;
    avatarCid: string;
    exists: boolean;
  };

  export type ProfileStructOutput = [
    username: string,
    displayName: string,
    bio: string,
    avatarCid: string,
    exists: boolean
  ] & {
    username: string;
    displayName: string;
    bio: string;
    avatarCid: string;
    exists: boolean;
  };
}

export interface PolygonChatRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "changeUsername"
      | "getConversationMeta"
      | "getProfile"
      | "isBlocked"
      | "ownerOfUsername"
      | "registerProfile"
      | "setBlockStatus"
      | "updateProfile"
      | "upsertMessagePointer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BlockStatusChanged"
      | "MessagePointerUpdated"
      | "ProfileCreated"
      | "ProfileUpdated"
      | "UsernameChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "changeUsername",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getConversationMeta",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBlocked",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerOfUsername",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProfile",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setBlockStatus",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProfile",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "upsertMessagePointer",
    values: [AddressLike, string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "changeUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConversationMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProfile", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isBlocked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownerOfUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBlockStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upsertMessagePointer",
    data: BytesLike
  ): Result;
}

export namespace BlockStatusChangedEvent {
  export type InputTuple = [
    owner: AddressLike,
    target: AddressLike,
    isBlocked: boolean
  ];
  export type OutputTuple = [owner: string, target: string, isBlocked: boolean];
  export interface OutputObject {
    owner: string;
    target: string;
    isBlocked: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessagePointerUpdatedEvent {
  export type InputTuple = [
    conversationId: BytesLike,
    sender: AddressLike,
    recipient: AddressLike,
    cid: string,
    contentHash: BytesLike,
    messageCount: BigNumberish
  ];
  export type OutputTuple = [
    conversationId: string,
    sender: string,
    recipient: string,
    cid: string,
    contentHash: string,
    messageCount: bigint
  ];
  export interface OutputObject {
    conversationId: string;
    sender: string;
    recipient: string;
    cid: string;
    contentHash: string;
    messageCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileCreatedEvent {
  export type InputTuple = [owner: AddressLike, username: string];
  export type OutputTuple = [owner: string, username: string];
  export interface OutputObject {
    owner: string;
    username: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileUpdatedEvent {
  export type InputTuple = [
    owner: AddressLike,
    avatarCid: string,
    bio: string,
    displayName: string
  ];
  export type OutputTuple = [
    owner: string,
    avatarCid: string,
    bio: string,
    displayName: string
  ];
  export interface OutputObject {
    owner: string;
    avatarCid: string;
    bio: string;
    displayName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsernameChangedEvent {
  export type InputTuple = [
    owner: AddressLike,
    oldUsername: string,
    newUsername: string
  ];
  export type OutputTuple = [
    owner: string,
    oldUsername: string,
    newUsername: string
  ];
  export interface OutputObject {
    owner: string;
    oldUsername: string;
    newUsername: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PolygonChatRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PolygonChatRegistry;
  waitForDeployment(): Promise<this>;

  interface: PolygonChatRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  changeUsername: TypedContractMethod<
    [newUsername: string],
    [void],
    "nonpayable"
  >;

  getConversationMeta: TypedContractMethod<
    [conversationId: BytesLike],
    [PolygonChatRegistry.ConversationMetaStructOutput],
    "view"
  >;

  getProfile: TypedContractMethod<
    [owner: AddressLike],
    [PolygonChatRegistry.ProfileStructOutput],
    "view"
  >;

  isBlocked: TypedContractMethod<
    [owner: AddressLike, target: AddressLike],
    [boolean],
    "view"
  >;

  ownerOfUsername: TypedContractMethod<[username: string], [string], "view">;

  registerProfile: TypedContractMethod<
    [username: string, avatarCid: string, bio: string, displayName: string],
    [void],
    "nonpayable"
  >;

  setBlockStatus: TypedContractMethod<
    [target: AddressLike, shouldBlock: boolean],
    [void],
    "nonpayable"
  >;

  updateProfile: TypedContractMethod<
    [avatarCid: string, bio: string, displayName: string],
    [void],
    "nonpayable"
  >;

  upsertMessagePointer: TypedContractMethod<
    [counterparty: AddressLike, cid: string, contentHash: BytesLike],
    [[string, bigint] & { conversationId: string; messageCount: bigint }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "changeUsername"
  ): TypedContractMethod<[newUsername: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getConversationMeta"
  ): TypedContractMethod<
    [conversationId: BytesLike],
    [PolygonChatRegistry.ConversationMetaStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProfile"
  ): TypedContractMethod<
    [owner: AddressLike],
    [PolygonChatRegistry.ProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isBlocked"
  ): TypedContractMethod<
    [owner: AddressLike, target: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "ownerOfUsername"
  ): TypedContractMethod<[username: string], [string], "view">;
  getFunction(
    nameOrSignature: "registerProfile"
  ): TypedContractMethod<
    [username: string, avatarCid: string, bio: string, displayName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBlockStatus"
  ): TypedContractMethod<
    [target: AddressLike, shouldBlock: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateProfile"
  ): TypedContractMethod<
    [avatarCid: string, bio: string, displayName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upsertMessagePointer"
  ): TypedContractMethod<
    [counterparty: AddressLike, cid: string, contentHash: BytesLike],
    [[string, bigint] & { conversationId: string; messageCount: bigint }],
    "nonpayable"
  >;

  getEvent(
    key: "BlockStatusChanged"
  ): TypedContractEvent<
    BlockStatusChangedEvent.InputTuple,
    BlockStatusChangedEvent.OutputTuple,
    BlockStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "MessagePointerUpdated"
  ): TypedContractEvent<
    MessagePointerUpdatedEvent.InputTuple,
    MessagePointerUpdatedEvent.OutputTuple,
    MessagePointerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileCreated"
  ): TypedContractEvent<
    ProfileCreatedEvent.InputTuple,
    ProfileCreatedEvent.OutputTuple,
    ProfileCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileUpdated"
  ): TypedContractEvent<
    ProfileUpdatedEvent.InputTuple,
    ProfileUpdatedEvent.OutputTuple,
    ProfileUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UsernameChanged"
  ): TypedContractEvent<
    UsernameChangedEvent.InputTuple,
    UsernameChangedEvent.OutputTuple,
    UsernameChangedEvent.OutputObject
  >;

  filters: {
    "BlockStatusChanged(address,address,bool)": TypedContractEvent<
      BlockStatusChangedEvent.InputTuple,
      BlockStatusChangedEvent.OutputTuple,
      BlockStatusChangedEvent.OutputObject
    >;
    BlockStatusChanged: TypedContractEvent<
      BlockStatusChangedEvent.InputTuple,
      BlockStatusChangedEvent.OutputTuple,
      BlockStatusChangedEvent.OutputObject
    >;

    "MessagePointerUpdated(bytes32,address,address,string,bytes32,uint256)": TypedContractEvent<
      MessagePointerUpdatedEvent.InputTuple,
      MessagePointerUpdatedEvent.OutputTuple,
      MessagePointerUpdatedEvent.OutputObject
    >;
    MessagePointerUpdated: TypedContractEvent<
      MessagePointerUpdatedEvent.InputTuple,
      MessagePointerUpdatedEvent.OutputTuple,
      MessagePointerUpdatedEvent.OutputObject
    >;

    "ProfileCreated(address,string)": TypedContractEvent<
      ProfileCreatedEvent.InputTuple,
      ProfileCreatedEvent.OutputTuple,
      ProfileCreatedEvent.OutputObject
    >;
    ProfileCreated: TypedContractEvent<
      ProfileCreatedEvent.InputTuple,
      ProfileCreatedEvent.OutputTuple,
      ProfileCreatedEvent.OutputObject
    >;

    "ProfileUpdated(address,string,string,string)": TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;
    ProfileUpdated: TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;

    "UsernameChanged(address,string,string)": TypedContractEvent<
      UsernameChangedEvent.InputTuple,
      UsernameChangedEvent.OutputTuple,
      UsernameChangedEvent.OutputObject
    >;
    UsernameChanged: TypedContractEvent<
      UsernameChangedEvent.InputTuple,
      UsernameChangedEvent.OutputTuple,
      UsernameChangedEvent.OutputObject
    >;
  };
}
